// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScrambleCoin.Infrastructure.Persistence;

#nullable disable

namespace ScrambleCoin.Infrastructure.Migrations
{
    [DbContext(typeof(ScrambleCoinDbContext))]
    [Migration("20260502071609_AddBotRegistration")]
    partial class AddBotRegistration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScrambleCoin.Infrastructure.Persistence.Records.BotRegistrationRecord", b =>
                {
                    b.Property<Guid>("Token")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Token");

                    b.ToTable("BotRegistrations", (string)null);
                });

            modelBuilder.Entity("ScrambleCoin.Infrastructure.Persistence.Records.GameRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BoardStateJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BoardState");

                    b.Property<int?>("CurrentPhase")
                        .HasColumnType("int");

                    b.Property<string>("LineupPlayerOneJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LineupPlayerOne");

                    b.Property<string>("LineupPlayerTwoJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LineupPlayerTwo");

                    b.Property<Guid?>("MovePhaseActivePlayer")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MovedPieceIdsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MovedPieceIds");

                    b.Property<string>("PiecesOnBoardJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PiecesOnBoard");

                    b.Property<string>("PlacePhaseDoneJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PlacePhaseDone");

                    b.Property<Guid>("PlayerOne")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerTwo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScoresJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Scores");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Games", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
