// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScrambleCoin.Infrastructure.Persistence;

#nullable disable

namespace ScrambleCoin.Infrastructure.Migrations
{
    [DbContext(typeof(ScrambleCoinDbContext))]
    [Migration("20260529100620_AddLastMoveAtToGameRecord")]
    partial class AddLastMoveAtToGameRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScrambleCoin.Domain.Entities.BotUnlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DefeatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UnlockedPieceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VillainId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("VillainId");

                    b.HasIndex("BotId", "VillainId");

                    b.ToTable("BotUnlocks", (string)null);
                });

            modelBuilder.Entity("ScrambleCoin.Domain.Entities.VillainNodeParent", b =>
                {
                    b.Property<string>("ChildVillainId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ParentVillainId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ChildVillainId", "ParentVillainId");

                    b.ToTable("VillainNodeParents", (string)null);
                });

            modelBuilder.Entity("ScrambleCoin.Domain.Entities.VillainTreeNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("UnlockedPieceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VillainId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VillainName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("VillainId")
                        .IsUnique();

                    b.ToTable("VillainTreeNodes", (string)null);
                });

            modelBuilder.Entity("ScrambleCoin.Infrastructure.Persistence.Records.BotRegistrationRecord", b =>
                {
                    b.Property<Guid>("Token")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Token");

                    b.ToTable("BotRegistrations", (string)null);
                });

            modelBuilder.Entity("ScrambleCoin.Infrastructure.Persistence.Records.GameRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BoardStateJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BoardState");

                    b.Property<int?>("CurrentPhase")
                        .HasColumnType("int");

                    b.Property<int>("GameMode")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastMoveAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LineupPlayerOneJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LineupPlayerOne");

                    b.Property<string>("LineupPlayerTwoJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LineupPlayerTwo");

                    b.Property<Guid?>("MovePhaseActivePlayer")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MovedPieceIdsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MovedPieceIds");

                    b.Property<string>("PiecesOnBoardJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PiecesOnBoard");

                    b.Property<string>("PlacePhaseDoneJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PlacePhaseDone");

                    b.Property<Guid>("PlayerOne")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerTwo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScoresJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Scores");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("int");

                    b.Property<string>("VillainId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("ScrambleCoin.Infrastructure.Persistence.Records.RankingTrackRecord", b =>
                {
                    b.Property<Guid>("BotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BotName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Draws")
                        .HasColumnType("int");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<string>("MilestonesHitJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MilestonesHit");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("BotId");

                    b.ToTable("RankingTracks", (string)null);
                });

            modelBuilder.Entity("ScrambleCoin.Infrastructure.Persistence.Records.TournamentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GroupMatchesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GroupMatches");

                    b.Property<string>("KnockoutMatchesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KnockoutMatches");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ParticipantsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Participants");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TopN")
                        .HasColumnType("int");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Tournaments", (string)null);
                });

            modelBuilder.Entity("ScrambleCoin.Domain.Entities.BotUnlock", b =>
                {
                    b.HasOne("ScrambleCoin.Domain.Entities.VillainTreeNode", null)
                        .WithMany()
                        .HasForeignKey("VillainId")
                        .HasPrincipalKey("VillainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScrambleCoin.Domain.Entities.VillainNodeParent", b =>
                {
                    b.HasOne("ScrambleCoin.Domain.Entities.VillainTreeNode", null)
                        .WithMany("ParentLinks")
                        .HasForeignKey("ChildVillainId")
                        .HasPrincipalKey("VillainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScrambleCoin.Domain.Entities.VillainTreeNode", b =>
                {
                    b.Navigation("ParentLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
